version: '3'
services:
    backend:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - ./app:/srv/app
        container_name: backend
        command: npm run start-dev --prefix /srv/app
    db:
        container_name: mysql
        ports:
            - '3306:3306'
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
            - ./app:/srv/app
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog_db
            MYSQL_USER: blog_user
            MYSQL_PASSWORD: blog_pw
            MYSQL_ROOT_HOST: '%'

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db_data: