version: '3'
services:
    backend:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - ./app:/srv/app
        container_name: backend
        command: npm start --prefix /srv/app
    db:
        container_name: mysql
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog_db
            MYSQL_USER: blog_user
            MYSQL_PASSWORD: blog_pw

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db_data: