CREATE TABLE IF NOT EXISTS posts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(768),
  slug VARCHAR(768) NOT NULL UNIQUE,
  content TEXT,
  snippet VARCHAR(1024),
  tags VARCHAR(1024),
  published BOOLEAN NOT NULL DEFAULT FALSE,
  datePublished DATETIME,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME
);